set_property CFGBVS GND                               [current_design]
set_property CONFIG_VOLTAGE 1.8                       [current_design]

set_property BOARD_PIN {clk_p} [get_ports {sys_clock_p}]
set_property BOARD_PIN {clk_n} [get_ports {sys_clock_n}]
create_clock -name sys_diff_clk -period 5.0 [get_ports sys_clock_p]
set_input_jitter [get_clocks -of_objects [get_ports sys_clock_p]] 0.5
create_clock -name JTCK -period 100.0 [get_ports {jtag_jtag_TCK}]
set_input_jitter JTCK 0.5
create_clock -name pcie_ref_clk -period 10.0 [get_ports {pciePorts_REFCLK_rxp}]
set_input_jitter pcie_ref_clk 0.5


set_clock_groups -asynchronous \
  -group [list [get_clocks { \
      sys_diff_clk \
    }]] \
  -group [list [get_clocks { \
      txoutclk \
      userclk1 \
    }]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out1 \
    }]]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out2 \
    }]]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out3 \
    }]]] \
  -group [list [get_clocks { \
      JTCK \
    }]] \
  -group [list [get_clocks -of_objects [get_pins { \
      mod_1/clockctrlClockDomainWrapper/clockctrl_0/mmcme2_adv_inst/CLKOUT0 \
    }]]]

# Nah, definitelly quit here. Going to put the false path in the clock


set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
set_property PACKAGE_PIN {BB23} [get_ports {jtag_jtag_TCK}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TCK}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TCK}]
set_property PACKAGE_PIN {BA21} [get_ports {jtag_jtag_TMS}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TMS}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TMS}]
set_property PACKAGE_PIN {BB21} [get_ports {jtag_jtag_TDI}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDI}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDI}]
set_property PACKAGE_PIN {BB24} [get_ports {jtag_jtag_TDO}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDO}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDO}]
set_property PACKAGE_PIN {AT32} [get_ports {uart_ctsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_ctsn}]
set_property IOB {TRUE} [get_ports {uart_ctsn}]
set_property PACKAGE_PIN {AR34} [get_ports {uart_rtsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rtsn}]
set_property IOB {TRUE} [ get_ports {uart_rtsn}]
set_property PACKAGE_PIN {AU33} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_ports {uart_rxd}]
set_property PACKAGE_PIN {AU36} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_txd}]
set_property IOB {TRUE} [get_ports {uart_txd}]
set_property PACKAGE_PIN {AN30} [get_ports {sdio_sdio_clk}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_clk}]
set_property IOB {TRUE} [get_ports {sdio_sdio_clk}]
set_property PACKAGE_PIN {AP30} [get_ports {sdio_sdio_cmd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_cmd}]
set_property IOB {TRUE} [get_ports {sdio_sdio_cmd}]
set_property PACKAGE_PIN {AR30} [get_ports {sdio_sdio_dat_0}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_0}]
set_property IOB {TRUE} [get_ports {sdio_sdio_dat_0}]
set_property PACKAGE_PIN {AU31} [get_ports {sdio_sdio_dat_1}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_1}]
set_property IOB {TRUE} [get_ports {sdio_sdio_dat_1}]
set_property PACKAGE_PIN {AV31} [get_ports {sdio_sdio_dat_2}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_2}]
set_property IOB {TRUE} [get_ports {sdio_sdio_dat_2}]
set_property PACKAGE_PIN {AT30} [get_ports {sdio_sdio_dat_3}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_3}]
set_property IOB {TRUE} [get_ports {sdio_sdio_dat_3}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_cmd}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_0}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_1}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_2}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_3}]
set_property BOARD_PIN {leds_8bits_tri_o_0} [get_ports {gpio_out[0]}]
set_property BOARD_PIN {leds_8bits_tri_o_1} [get_ports {gpio_out[1]}]
set_property BOARD_PIN {leds_8bits_tri_o_2} [get_ports {gpio_out[2]}]
set_property BOARD_PIN {leds_8bits_tri_o_3} [get_ports {gpio_out[3]}]
set_property BOARD_PIN {leds_8bits_tri_o_4} [get_ports {gpio_out[4]}]
set_property BOARD_PIN {leds_8bits_tri_o_5} [get_ports {gpio_out[5]}]
set_property BOARD_PIN {leds_8bits_tri_o_6} [get_ports {gpio_out[6]}]
set_property BOARD_PIN {leds_8bits_tri_o_7} [get_ports {gpio_out[7]}]
set_property PACKAGE_PIN {AV30} [get_ports {gpio_in[0]}]
set_property PACKAGE_PIN {AY33} [get_ports {gpio_in[1]}]
set_property PACKAGE_PIN {BA31} [get_ports {gpio_in[2]}]
set_property PACKAGE_PIN {BA32} [get_ports {gpio_in[3]}]
set_property PACKAGE_PIN {AW30} [get_ports {gpio_in[4]}]
set_property PACKAGE_PIN {AY30} [get_ports {gpio_in[5]}]
set_property PACKAGE_PIN {BA30} [get_ports {gpio_in[6]}]
set_property PACKAGE_PIN {BB31} [get_ports {gpio_in[7]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[0]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[1]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[2]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[3]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[4]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[5]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[6]}]
set_property IOSTANDARD {LVCMOS18} [get_ports {gpio_in[7]}]
set_property BOARD_PIN {reset} [get_ports {rst_0}]
set_property PACKAGE_PIN {AP40} [get_ports {rst_1}]
set_property IOSTANDARD {LVCMOS18} [get_ports {rst_1}]
set_property PACKAGE_PIN {AV39} [get_ports {rst_2}]
set_property IOSTANDARD {LVCMOS18} [get_ports {rst_2}]
set_property PACKAGE_PIN {AR40} [get_ports {rst_3}]
set_property IOSTANDARD {LVCMOS18} [get_ports {rst_3}]

#set_property PACKAGE_PIN {N38} [get_ports {qspi_qspi_cs}] # FMC1_HPC_LA_P_10
#set_property PACKAGE_PIN {M39} [get_ports {qspi_qspi_sck}] # FMC1_HPC_LA_N_10
#set_property PACKAGE_PIN {F40} [get_ports {qspi_qspi_miso}] # FMC1_HPC_LA_P_11
#set_property PACKAGE_PIN {F41} [get_ports {qspi_qspi_mosi}] # FMC1_HPC_LA_N_11
#set_property PACKAGE_PIN {R40} [get_ports {qspi_qspi_wp}] # FMC1_HPC_LA_P_12
#set_property PACKAGE_PIN {P40} [get_ports {qspi_qspi_hold}] # FMC1_HPC_LA_N_12
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_cs}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_sck}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_miso}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_mosi}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_wp}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {qspi_qspi_hold}]
#set_property PACKAGE_PIN {AK39} [get_ports {USB_0_WireDataIn[0]}] # FMC2_HPC_LA_P_2
#set_property PACKAGE_PIN {AL39} [get_ports {USB_0_WireDataIn[1]}] # FMC2_HPC_LA_N_2
#set_property PACKAGE_PIN {AJ42} [get_ports {USB_0_WireDataOut[0]}] # FMC2_HPC_LA_P_3
#set_property PACKAGE_PIN {AK42} [get_ports {USB_0_WireDataOut[1]}] # FMC2_HPC_LA_N_3
#set_property PACKAGE_PIN {AF42} [get_ports {USB_0_WireCtrlOut}] # FMC2_HPC_LA_P_5
#set_property PACKAGE_PIN {AG42} [get_ports {USB_0_FullSpeed}] # FMC2_HPC_LA_N_5
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_WireDataIn[0]}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_WireDataIn[1]}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_WireDataOut[0]}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_WireDataOut[1]}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_WireCtrlOut}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {USB_0_FullSpeed}]
#set_property PACKAGE_PIN {A10} [get_ports {pciePorts_REFCLK_rxp}] # FMC1_HPC_GBTCLK_M2C_P_0
#set_property PACKAGE_PIN {A9} [get_ports {pciePorts_REFCLK_rxn}] # FMC1_HPC_GBTCLK_M2C_N_0
#set_property PACKAGE_PIN {H4} [get_ports {pciePorts_pci_exp_txp}] # FMC1_HPC_DP_C2M_P_5
#set_property PACKAGE_PIN {H3} [get_ports {pciePorts_pci_exp_txn}] # FMC1_HPC_DP_C2M_N_5
#set_property PACKAGE_PIN {G6} [get_ports {pciePorts_pci_exp_rxp}] # FMC1_HPC_DP_M2C_P_5
#set_property PACKAGE_PIN {G5} [get_ports {pciePorts_pci_exp_rxn}] # FMC1_HPC_DP_M2C_N_5

################################################################################
# CLOCKS
################################################################################

# User Clock
set_property PACKAGE_PIN AK34 [get_ports USER_CLOCK_P]
set_property IOSTANDARD LVDS [get_ports USER_CLOCK_P]
set_property PACKAGE_PIN AL34 [get_ports USER_CLOCK_N]
set_property IOSTANDARD LVDS [get_ports USER_CLOCK_N]

# User SMA Clock
set_property PACKAGE_PIN AJ32 [get_ports USER_SMA_CLOCK_P]
set_property IOSTANDARD LVCMOS18 [get_ports USER_SMA_CLOCK_P]
set_property PACKAGE_PIN AK32 [get_ports USER_SMA_CLOCK_N]
set_property IOSTANDARD LVCMOS18 [get_ports USER_SMA_CLOCK_N]

################################################################################
# FMC Connectors
################################################################################

# FMC1
set_property PACKAGE_PIN H40 [get_ports FMC1_HPC_LA_P_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_4]
set_property PACKAGE_PIN H41 [get_ports FMC1_HPC_LA_N_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_4]
set_property PACKAGE_PIN H39 [get_ports FMC1_HPC_LA_P_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_13]
set_property PACKAGE_PIN G39 [get_ports FMC1_HPC_LA_N_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_13]
set_property PACKAGE_PIN G41 [get_ports FMC1_HPC_LA_P_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_7]
set_property PACKAGE_PIN G42 [get_ports FMC1_HPC_LA_N_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_7]
set_property PACKAGE_PIN F40 [get_ports FMC1_HPC_LA_P_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_11]
set_property PACKAGE_PIN F41 [get_ports FMC1_HPC_LA_N_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_11]
set_property PACKAGE_PIN J40 [get_ports FMC1_HPC_LA_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_1]
set_property PACKAGE_PIN J41 [get_ports FMC1_HPC_LA_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_1]
set_property PACKAGE_PIN K39 [get_ports FMC1_HPC_LA_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_0]
set_property PACKAGE_PIN K40 [get_ports FMC1_HPC_LA_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_0]
set_property PACKAGE_PIN L39 [get_ports FMC1_HPC_CLK_M2C_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_CLK_M2C_P_0]
set_property PACKAGE_PIN L40 [get_ports FMC1_HPC_CLK_M2C_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_CLK_M2C_N_0]
set_property PACKAGE_PIN M41 [get_ports FMC1_HPC_LA_P_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_5]
set_property PACKAGE_PIN L41 [get_ports FMC1_HPC_LA_N_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_5]
set_property PACKAGE_PIN K42 [get_ports FMC1_HPC_LA_P_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_6]
set_property PACKAGE_PIN J42 [get_ports FMC1_HPC_LA_N_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_6]
set_property PACKAGE_PIN M42 [get_ports FMC1_HPC_LA_P_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_3]
set_property PACKAGE_PIN L42 [get_ports FMC1_HPC_LA_N_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_3]
set_property PACKAGE_PIN K37 [get_ports FMC1_HPC_LA_P_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_16]
set_property PACKAGE_PIN K38 [get_ports FMC1_HPC_LA_N_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_16]
set_property PACKAGE_PIN M36 [get_ports FMC1_HPC_LA_P_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_15]
set_property PACKAGE_PIN L37 [get_ports FMC1_HPC_LA_N_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_15]
set_property PACKAGE_PIN P41 [get_ports FMC1_HPC_LA_P_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_2]
set_property PACKAGE_PIN N41 [get_ports FMC1_HPC_LA_N_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_2]
set_property PACKAGE_PIN M37 [get_ports FMC1_HPC_LA_P_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_8]
set_property PACKAGE_PIN M38 [get_ports FMC1_HPC_LA_N_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_8]
set_property PACKAGE_PIN R42 [get_ports FMC1_HPC_LA_P_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_9]
set_property PACKAGE_PIN P42 [get_ports FMC1_HPC_LA_N_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_9]
set_property PACKAGE_PIN N38 [get_ports FMC1_HPC_LA_P_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_10]
set_property PACKAGE_PIN M39 [get_ports FMC1_HPC_LA_N_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_10]
set_property PACKAGE_PIN R40 [get_ports FMC1_HPC_LA_P_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_12]
set_property PACKAGE_PIN P40 [get_ports FMC1_HPC_LA_N_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_12]
set_property PACKAGE_PIN N39 [get_ports FMC1_HPC_LA_P_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_14]
set_property PACKAGE_PIN N40 [get_ports FMC1_HPC_LA_N_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_14]

set_property PACKAGE_PIN K29 [get_ports FMC1_HPC_LA_P_25]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_25]
set_property PACKAGE_PIN K30 [get_ports FMC1_HPC_LA_N_25]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_25]
set_property PACKAGE_PIN J30 [get_ports FMC1_HPC_LA_P_26]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_26]
set_property PACKAGE_PIN H30 [get_ports FMC1_HPC_LA_N_26]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_26]
set_property PACKAGE_PIN L29 [get_ports FMC1_HPC_LA_P_28]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_28]
set_property PACKAGE_PIN L30 [get_ports FMC1_HPC_LA_N_28]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_28]
set_property PACKAGE_PIN J31 [get_ports FMC1_HPC_LA_P_27]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_27]
set_property PACKAGE_PIN H31 [get_ports FMC1_HPC_LA_N_27]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_27]
set_property PACKAGE_PIN M32 [get_ports FMC1_HPC_LA_P_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_18]
set_property PACKAGE_PIN L32 [get_ports FMC1_HPC_LA_N_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_18]
set_property PACKAGE_PIN L31 [get_ports FMC1_HPC_LA_P_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_17]
set_property PACKAGE_PIN K32 [get_ports FMC1_HPC_LA_N_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_17]
set_property PACKAGE_PIN N30 [get_ports FMC1_HPC_CLK_M2C_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_CLK_M2C_P_1]
set_property PACKAGE_PIN M31 [get_ports FMC1_HPC_CLK_M2C_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_CLK_M2C_N_1]
set_property PACKAGE_PIN P30 [get_ports FMC1_HPC_LA_P_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_23]
set_property PACKAGE_PIN N31 [get_ports FMC1_HPC_LA_N_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_23]
set_property PACKAGE_PIN M28 [get_ports FMC1_HPC_LA_P_31]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_31]
set_property PACKAGE_PIN M29 [get_ports FMC1_HPC_LA_N_31]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_31]
set_property PACKAGE_PIN R28 [get_ports FMC1_HPC_LA_P_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_22]
set_property PACKAGE_PIN P28 [get_ports FMC1_HPC_LA_N_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_22]
set_property PACKAGE_PIN N28 [get_ports FMC1_HPC_LA_P_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_21]
set_property PACKAGE_PIN N29 [get_ports FMC1_HPC_LA_N_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_21]
set_property PACKAGE_PIN R30 [get_ports FMC1_HPC_LA_P_24]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_24]
set_property PACKAGE_PIN P31 [get_ports FMC1_HPC_LA_N_24]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_24]
set_property PACKAGE_PIN U31 [get_ports FMC1_HPC_LA_P_33]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_33]
set_property PACKAGE_PIN T31 [get_ports FMC1_HPC_LA_N_33]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_33]
set_property PACKAGE_PIN V30 [get_ports FMC1_HPC_LA_P_30]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_30]
set_property PACKAGE_PIN V31 [get_ports FMC1_HPC_LA_N_30]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_30]
set_property PACKAGE_PIN T29 [get_ports FMC1_HPC_LA_P_29]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_29]
set_property PACKAGE_PIN T30 [get_ports FMC1_HPC_LA_N_29]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_29]
set_property PACKAGE_PIN W30 [get_ports FMC1_HPC_LA_P_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_19]
set_property PACKAGE_PIN W31 [get_ports FMC1_HPC_LA_N_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_19]
set_property PACKAGE_PIN V29 [get_ports FMC1_HPC_LA_P_32]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_32]
set_property PACKAGE_PIN U29 [get_ports FMC1_HPC_LA_N_32]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_32]
set_property PACKAGE_PIN Y29 [get_ports FMC1_HPC_LA_P_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_P_20]
set_property PACKAGE_PIN Y30 [get_ports FMC1_HPC_LA_N_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_LA_N_20]

set_property PACKAGE_PIN B36 [get_ports FMC1_HPC_HA_P_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_13]
set_property PACKAGE_PIN A37 [get_ports FMC1_HPC_HA_N_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_13]
set_property PACKAGE_PIN B34 [get_ports FMC1_HPC_HA_P_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_20]
set_property PACKAGE_PIN A34 [get_ports FMC1_HPC_HA_N_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_20]
set_property PACKAGE_PIN B39 [get_ports FMC1_HPC_HA_P_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_16]
set_property PACKAGE_PIN A39 [get_ports FMC1_HPC_HA_N_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_16]
set_property PACKAGE_PIN A35 [get_ports FMC1_HPC_HA_P_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_23]
set_property PACKAGE_PIN A36 [get_ports FMC1_HPC_HA_N_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_23]
set_property PACKAGE_PIN C38 [get_ports FMC1_HPC_HA_P_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_7]
set_property PACKAGE_PIN C39 [get_ports FMC1_HPC_HA_N_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_7]
set_property PACKAGE_PIN B37 [get_ports FMC1_HPC_HA_P_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_12]
set_property PACKAGE_PIN B38 [get_ports FMC1_HPC_HA_N_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_12]
set_property PACKAGE_PIN E32 [get_ports FMC1_HPC_HA_P_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_9]
set_property PACKAGE_PIN D32 [get_ports FMC1_HPC_HA_N_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_9]
set_property PACKAGE_PIN B32 [get_ports FMC1_HPC_HA_P_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_19]
set_property PACKAGE_PIN B33 [get_ports FMC1_HPC_HA_N_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_19]
set_property PACKAGE_PIN E33 [get_ports FMC1_HPC_HA_P_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_2]
set_property PACKAGE_PIN D33 [get_ports FMC1_HPC_HA_N_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_2]
set_property PACKAGE_PIN C33 [get_ports FMC1_HPC_HA_P_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_15]
set_property PACKAGE_PIN C34 [get_ports FMC1_HPC_HA_N_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_15]
set_property PACKAGE_PIN D35 [get_ports FMC1_HPC_HA_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_1]
set_property PACKAGE_PIN D36 [get_ports FMC1_HPC_HA_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_1]
set_property PACKAGE_PIN C35 [get_ports FMC1_HPC_HA_P_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_17]
set_property PACKAGE_PIN C36 [get_ports FMC1_HPC_HA_N_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_17]
set_property PACKAGE_PIN E34 [get_ports FMC1_HPC_HA_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_0]
set_property PACKAGE_PIN E35 [get_ports FMC1_HPC_HA_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_0]
set_property PACKAGE_PIN D37 [get_ports FMC1_HPC_HA_P_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_21]
set_property PACKAGE_PIN D38 [get_ports FMC1_HPC_HA_N_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_21]
set_property PACKAGE_PIN G32 [get_ports FMC1_HPC_HA_P_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_5]
set_property PACKAGE_PIN F32 [get_ports FMC1_HPC_HA_N_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_5]
set_property PACKAGE_PIN F36 [get_ports FMC1_HPC_HA_P_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_22]
set_property PACKAGE_PIN F37 [get_ports FMC1_HPC_HA_N_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_22]
set_property PACKAGE_PIN F34 [get_ports FMC1_HPC_HA_P_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_4]
set_property PACKAGE_PIN F35 [get_ports FMC1_HPC_HA_N_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_4]
set_property PACKAGE_PIN H33 [get_ports FMC1_HPC_HA_P_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_3]
set_property PACKAGE_PIN G33 [get_ports FMC1_HPC_HA_N_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_3]
set_property PACKAGE_PIN E37 [get_ports FMC1_HPC_HA_P_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_14]
set_property PACKAGE_PIN E38 [get_ports FMC1_HPC_HA_N_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_14]
set_property PACKAGE_PIN G36 [get_ports FMC1_HPC_HA_P_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_6]
set_property PACKAGE_PIN G37 [get_ports FMC1_HPC_HA_N_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_6]
set_property PACKAGE_PIN F39 [get_ports FMC1_HPC_HA_P_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_18]
set_property PACKAGE_PIN E39 [get_ports FMC1_HPC_HA_N_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_18]
set_property PACKAGE_PIN J37 [get_ports FMC1_HPC_HA_P_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_11]
set_property PACKAGE_PIN J38 [get_ports FMC1_HPC_HA_N_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_11]
set_property PACKAGE_PIN H38 [get_ports FMC1_HPC_HA_P_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_10]
set_property PACKAGE_PIN G38 [get_ports FMC1_HPC_HA_N_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_10]
set_property PACKAGE_PIN J36 [get_ports FMC1_HPC_HA_P_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_P_8]
set_property PACKAGE_PIN H36 [get_ports FMC1_HPC_HA_N_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HA_N_8]

set_property PACKAGE_PIN H24 [get_ports FMC1_HPC_HB_P_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_4]
set_property PACKAGE_PIN G24 [get_ports FMC1_HPC_HB_N_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_4]
set_property PACKAGE_PIN J21 [get_ports FMC1_HPC_HB_P_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_14]
set_property PACKAGE_PIN H21 [get_ports FMC1_HPC_HB_N_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_14]
set_property PACKAGE_PIN H25 [get_ports FMC1_HPC_HB_P_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_8]
set_property PACKAGE_PIN H26 [get_ports FMC1_HPC_HB_N_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_8]
set_property PACKAGE_PIN G21 [get_ports FMC1_HPC_HB_P_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_18]
set_property PACKAGE_PIN G22 [get_ports FMC1_HPC_HB_N_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_18]
set_property PACKAGE_PIN G26 [get_ports FMC1_HPC_HB_P_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_7]
set_property PACKAGE_PIN G27 [get_ports FMC1_HPC_HB_N_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_7]
set_property PACKAGE_PIN H23 [get_ports FMC1_HPC_HB_P_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_9]
set_property PACKAGE_PIN G23 [get_ports FMC1_HPC_HB_N_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_9]
set_property PACKAGE_PIN G28 [get_ports FMC1_HPC_HB_P_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_3]
set_property PACKAGE_PIN G29 [get_ports FMC1_HPC_HB_N_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_3]
set_property PACKAGE_PIN K28 [get_ports FMC1_HPC_HB_P_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_2]
set_property PACKAGE_PIN J28 [get_ports FMC1_HPC_HB_N_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_2]
set_property PACKAGE_PIN H28 [get_ports FMC1_HPC_HB_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_1]
set_property PACKAGE_PIN H29 [get_ports FMC1_HPC_HB_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_1]
set_property PACKAGE_PIN K27 [get_ports FMC1_HPC_HB_P_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_5]
set_property PACKAGE_PIN J27 [get_ports FMC1_HPC_HB_N_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_5]
set_property PACKAGE_PIN K24 [get_ports FMC1_HPC_HB_P_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_12]
set_property PACKAGE_PIN K25 [get_ports FMC1_HPC_HB_N_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_12]
set_property PACKAGE_PIN J25 [get_ports FMC1_HPC_HB_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_0]
set_property PACKAGE_PIN J26 [get_ports FMC1_HPC_HB_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_0]
set_property PACKAGE_PIN M24 [get_ports FMC1_HPC_HB_P_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_17]
set_property PACKAGE_PIN L24 [get_ports FMC1_HPC_HB_N_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_17]
set_property PACKAGE_PIN K23 [get_ports FMC1_HPC_HB_P_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_6]
set_property PACKAGE_PIN J23 [get_ports FMC1_HPC_HB_N_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_6]
set_property PACKAGE_PIN M22 [get_ports FMC1_HPC_HB_P_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_10]
set_property PACKAGE_PIN L22 [get_ports FMC1_HPC_HB_N_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_10]
set_property PACKAGE_PIN L25 [get_ports FMC1_HPC_HB_P_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_19]
set_property PACKAGE_PIN L26 [get_ports FMC1_HPC_HB_N_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_19]
set_property PACKAGE_PIN K22 [get_ports FMC1_HPC_HB_P_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_11]
set_property PACKAGE_PIN J22 [get_ports FMC1_HPC_HB_N_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_11]
set_property PACKAGE_PIN M21 [get_ports FMC1_HPC_HB_P_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_15]
set_property PACKAGE_PIN L21 [get_ports FMC1_HPC_HB_N_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_15]
set_property PACKAGE_PIN P21 [get_ports FMC1_HPC_HB_P_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_20]
set_property PACKAGE_PIN N21 [get_ports FMC1_HPC_HB_N_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_20]
set_property PACKAGE_PIN P25 [get_ports FMC1_HPC_HB_P_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_13]
set_property PACKAGE_PIN P26 [get_ports FMC1_HPC_HB_N_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_13]
set_property PACKAGE_PIN P22 [get_ports FMC1_HPC_HB_P_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_21]
set_property PACKAGE_PIN P23 [get_ports FMC1_HPC_HB_N_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_21]
set_property PACKAGE_PIN N25 [get_ports FMC1_HPC_HB_P_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_P_16]
set_property PACKAGE_PIN N26 [get_ports FMC1_HPC_HB_N_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_HB_N_16]

set_property PACKAGE_PIN M4 [get_ports FMC2_HPC_DP_C2M_P_1]
set_property PACKAGE_PIN N6 [get_ports FMC2_HPC_DP_M2C_P_1]
set_property PACKAGE_PIN M3 [get_ports FMC2_HPC_DP_C2M_N_1]
set_property PACKAGE_PIN N5 [get_ports FMC2_HPC_DP_M2C_N_1]
set_property PACKAGE_PIN N2 [get_ports FMC2_HPC_DP_C2M_P_0]
set_property PACKAGE_PIN P8 [get_ports FMC2_HPC_DP_M2C_P_0]
set_property PACKAGE_PIN N1 [get_ports FMC2_HPC_DP_C2M_N_0]
set_property PACKAGE_PIN P7 [get_ports FMC2_HPC_DP_M2C_N_0]
set_property PACKAGE_PIN F4 [get_ports FMC1_HPC_DP_C2M_P_7]
set_property PACKAGE_PIN E6 [get_ports FMC1_HPC_DP_M2C_P_7]
set_property PACKAGE_PIN F3 [get_ports FMC1_HPC_DP_C2M_N_7]
set_property PACKAGE_PIN E5 [get_ports FMC1_HPC_DP_M2C_N_7]
set_property PACKAGE_PIN G2 [get_ports FMC1_HPC_DP_C2M_P_6]
set_property PACKAGE_PIN F8 [get_ports FMC1_HPC_DP_M2C_P_6]
set_property PACKAGE_PIN G1 [get_ports FMC1_HPC_DP_C2M_N_6]
set_property PACKAGE_PIN E10 [get_ports FMC1_HPC_GBTCLK_M2C_P_1]
set_property PACKAGE_PIN F7 [get_ports FMC1_HPC_DP_M2C_N_6]
set_property PACKAGE_PIN E9 [get_ports FMC1_HPC_GBTCLK_M2C_N_1]

set_property PACKAGE_PIN H4 [get_ports FMC1_HPC_DP_C2M_P_5]
set_property PACKAGE_PIN G6 [get_ports FMC1_HPC_DP_M2C_P_5]
set_property PACKAGE_PIN H3 [get_ports FMC1_HPC_DP_C2M_N_5]
set_property PACKAGE_PIN G5 [get_ports FMC1_HPC_DP_M2C_N_5]
set_property PACKAGE_PIN J2 [get_ports FMC1_HPC_DP_C2M_P_4]
set_property PACKAGE_PIN H8 [get_ports FMC1_HPC_DP_M2C_P_4]
set_property PACKAGE_PIN J1 [get_ports FMC1_HPC_DP_C2M_N_4]
set_property PACKAGE_PIN H7 [get_ports FMC1_HPC_DP_M2C_N_4]
set_property PACKAGE_PIN B4 [get_ports FMC1_HPC_DP_C2M_P_3]
set_property PACKAGE_PIN A6 [get_ports FMC1_HPC_DP_M2C_P_3]
set_property PACKAGE_PIN B3 [get_ports FMC1_HPC_DP_C2M_N_3]
set_property PACKAGE_PIN A5 [get_ports FMC1_HPC_DP_M2C_N_3]
set_property PACKAGE_PIN C2 [get_ports FMC1_HPC_DP_C2M_P_2]
set_property PACKAGE_PIN B8 [get_ports FMC1_HPC_DP_M2C_P_2]
set_property PACKAGE_PIN C1 [get_ports FMC1_HPC_DP_C2M_N_2]
set_property PACKAGE_PIN A10 [get_ports FMC1_HPC_GBTCLK_M2C_P_0]
set_property PACKAGE_PIN B7 [get_ports FMC1_HPC_DP_M2C_N_2]
set_property PACKAGE_PIN A9 [get_ports FMC1_HPC_GBTCLK_M2C_N_0]

set_property PACKAGE_PIN D4 [get_ports FMC1_HPC_DP_C2M_P_1]
set_property PACKAGE_PIN C6 [get_ports FMC1_HPC_DP_M2C_P_1]
set_property PACKAGE_PIN D3 [get_ports FMC1_HPC_DP_C2M_N_1]
set_property PACKAGE_PIN C5 [get_ports FMC1_HPC_DP_M2C_N_1]
set_property PACKAGE_PIN E2 [get_ports FMC1_HPC_DP_C2M_P_0]
set_property PACKAGE_PIN D8 [get_ports FMC1_HPC_DP_M2C_P_0]
set_property PACKAGE_PIN E1 [get_ports FMC1_HPC_DP_C2M_N_0]
set_property PACKAGE_PIN D7 [get_ports FMC1_HPC_DP_M2C_N_0]

set_property PACKAGE_PIN AM31 [get_ports FMC1_HPC_PRSNT_M2C_B_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_PRSNT_M2C_B_LS]
set_property PACKAGE_PIN AN34 [get_ports FMC1_HPC_PG_M2C_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC1_HPC_PG_M2C_LS]

# FMC2
set_property PACKAGE_PIN AF35 [get_ports FMC2_HPC_HA_P_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_14]
set_property PACKAGE_PIN AF36 [get_ports FMC2_HPC_HA_N_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_14]
set_property PACKAGE_PIN AE37 [get_ports FMC2_HPC_HA_P_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_15]
set_property PACKAGE_PIN AF37 [get_ports FMC2_HPC_HA_N_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_15]
set_property PACKAGE_PIN AF34 [get_ports FMC2_HPC_HA_P_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_12]
set_property PACKAGE_PIN AG34 [get_ports FMC2_HPC_HA_N_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_12]
set_property PACKAGE_PIN AD36 [get_ports FMC2_HPC_HA_P_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_20]
set_property PACKAGE_PIN AD37 [get_ports FMC2_HPC_HA_N_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_20]
set_property PACKAGE_PIN AC35 [get_ports FMC2_HPC_HA_P_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_19]
set_property PACKAGE_PIN AC36 [get_ports FMC2_HPC_HA_N_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_19]
set_property PACKAGE_PIN AG36 [get_ports FMC2_HPC_HA_P_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_16]
set_property PACKAGE_PIN AH36 [get_ports FMC2_HPC_HA_N_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_16]
set_property PACKAGE_PIN Y37 [get_ports FMC2_HPC_HA_P_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_23]
set_property PACKAGE_PIN AA37 [get_ports FMC2_HPC_HA_N_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_23]
set_property PACKAGE_PIN Y35 [get_ports FMC2_HPC_HA_P_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_22]
set_property PACKAGE_PIN AA36 [get_ports FMC2_HPC_HA_N_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_22]
set_property PACKAGE_PIN AB36 [get_ports FMC2_HPC_HA_P_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_18]
set_property PACKAGE_PIN AB37 [get_ports FMC2_HPC_HA_N_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_18]
set_property PACKAGE_PIN AA34 [get_ports FMC2_HPC_HA_P_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_21]
set_property PACKAGE_PIN AA35 [get_ports FMC2_HPC_HA_N_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_21]
set_property PACKAGE_PIN AB31 [get_ports FMC2_HPC_HA_P_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_6]
set_property PACKAGE_PIN AB32 [get_ports FMC2_HPC_HA_N_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_6]
set_property PACKAGE_PIN AB33 [get_ports FMC2_HPC_HA_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_0]
set_property PACKAGE_PIN AC33 [get_ports FMC2_HPC_HA_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_0]
set_property PACKAGE_PIN AD32 [get_ports FMC2_HPC_HA_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_1]
set_property PACKAGE_PIN AD33 [get_ports FMC2_HPC_HA_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_1]
set_property PACKAGE_PIN AC34 [get_ports FMC2_HPC_HA_P_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_17]
set_property PACKAGE_PIN AD35 [get_ports FMC2_HPC_HA_N_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_17]
set_property PACKAGE_PIN AE32 [get_ports FMC2_HPC_HA_P_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_13]
set_property PACKAGE_PIN AE33 [get_ports FMC2_HPC_HA_N_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_13]
set_property PACKAGE_PIN AF31 [get_ports FMC2_HPC_HA_P_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_10]
set_property PACKAGE_PIN AF32 [get_ports FMC2_HPC_HA_N_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_10]
set_property PACKAGE_PIN AE34 [get_ports FMC2_HPC_HA_P_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_11]
set_property PACKAGE_PIN AE35 [get_ports FMC2_HPC_HA_N_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_11]
set_property PACKAGE_PIN AE29 [get_ports FMC2_HPC_HA_P_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_9]
set_property PACKAGE_PIN AE30 [get_ports FMC2_HPC_HA_N_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_9]
set_property PACKAGE_PIN Y32 [get_ports FMC2_HPC_HA_P_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_5]
set_property PACKAGE_PIN Y33 [get_ports FMC2_HPC_HA_N_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_5]
set_property PACKAGE_PIN AC31 [get_ports FMC2_HPC_HA_P_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_7]
set_property PACKAGE_PIN AD31 [get_ports FMC2_HPC_HA_N_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_7]
set_property PACKAGE_PIN AA31 [get_ports FMC2_HPC_HA_P_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_8]
set_property PACKAGE_PIN AA32 [get_ports FMC2_HPC_HA_N_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_8]
set_property PACKAGE_PIN AC30 [get_ports FMC2_HPC_HA_P_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_2]
set_property PACKAGE_PIN AD30 [get_ports FMC2_HPC_HA_N_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_2]
set_property PACKAGE_PIN AA29 [get_ports FMC2_HPC_HA_P_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_3]
set_property PACKAGE_PIN AA30 [get_ports FMC2_HPC_HA_N_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_3]
set_property PACKAGE_PIN AB29 [get_ports FMC2_HPC_HA_P_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_P_4]
set_property PACKAGE_PIN AC29 [get_ports FMC2_HPC_HA_N_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_HA_N_4]

set_property PACKAGE_PIN AB41 [get_ports FMC2_HPC_LA_P_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_10]
set_property PACKAGE_PIN AB42 [get_ports FMC2_HPC_LA_N_10]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_10]
set_property PACKAGE_PIN W40 [get_ports FMC2_HPC_LA_P_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_13]
set_property PACKAGE_PIN Y40 [get_ports FMC2_HPC_LA_N_13]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_13]
set_property PACKAGE_PIN Y39 [get_ports FMC2_HPC_LA_P_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_12]
set_property PACKAGE_PIN AA39 [get_ports FMC2_HPC_LA_N_12]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_12]
set_property PACKAGE_PIN Y42 [get_ports FMC2_HPC_LA_P_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_11]
set_property PACKAGE_PIN AA42 [get_ports FMC2_HPC_LA_N_11]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_11]
set_property PACKAGE_PIN AB38 [get_ports FMC2_HPC_LA_P_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_14]
set_property PACKAGE_PIN AB39 [get_ports FMC2_HPC_LA_N_14]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_14]

set_property PACKAGE_PIN AC38 [get_ports FMC2_HPC_LA_P_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_15]
set_property PACKAGE_PIN AC39 [get_ports FMC2_HPC_LA_N_15]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_15]
set_property PACKAGE_PIN AD42 [get_ports FMC2_HPC_LA_P_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_8]
set_property PACKAGE_PIN AE42 [get_ports FMC2_HPC_LA_N_8]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_8]
set_property PACKAGE_PIN AD38 [get_ports FMC2_HPC_LA_P_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_6]
set_property PACKAGE_PIN AE38 [get_ports FMC2_HPC_LA_N_6]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_6]
set_property PACKAGE_PIN AC40 [get_ports FMC2_HPC_LA_P_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_7]
set_property PACKAGE_PIN AC41 [get_ports FMC2_HPC_LA_N_7]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_7]

set_property PACKAGE_PIN AD40 [get_ports FMC2_HPC_LA_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_0]
set_property PACKAGE_PIN AD41 [get_ports FMC2_HPC_LA_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_0]
set_property PACKAGE_PIN AF39 [get_ports FMC2_HPC_CLK_M2C_P_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_CLK_M2C_P_0]
set_property PACKAGE_PIN AF40 [get_ports FMC2_HPC_CLK_M2C_N_0]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_CLK_M2C_N_0]
set_property PACKAGE_PIN AF41 [get_ports FMC2_HPC_LA_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_1]
set_property PACKAGE_PIN AG41 [get_ports FMC2_HPC_LA_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_1]

set_property PACKAGE_PIN AF29 [get_ports FMC2_HPC_PG_M2C_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_PG_M2C_LS]
set_property PACKAGE_PIN AG32 [get_ports FMC2_HPC_PRSNT_M2C_B_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_PRSNT_M2C_B_LS]

set_property PACKAGE_PIN AF42 [get_ports FMC2_HPC_LA_P_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_5]
set_property PACKAGE_PIN AG42 [get_ports FMC2_HPC_LA_N_5]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_5]

set_property PACKAGE_PIN AJ38 [get_ports FMC2_HPC_LA_P_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_9]
set_property PACKAGE_PIN AK38 [get_ports FMC2_HPC_LA_N_9]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_9]

set_property PACKAGE_PIN AL41 [get_ports FMC2_HPC_LA_P_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_4]
set_property PACKAGE_PIN AL42 [get_ports FMC2_HPC_LA_N_4]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_4]
set_property PACKAGE_PIN AJ40 [get_ports FMC2_HPC_LA_P_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_16]
set_property PACKAGE_PIN AJ41 [get_ports FMC2_HPC_LA_N_16]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_16]
set_property PACKAGE_PIN AK39 [get_ports FMC2_HPC_LA_P_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_2]
set_property PACKAGE_PIN AL39 [get_ports FMC2_HPC_LA_N_2]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_2]
set_property PACKAGE_PIN AJ42 [get_ports FMC2_HPC_LA_P_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_3]
set_property PACKAGE_PIN AK42 [get_ports FMC2_HPC_LA_N_3]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_3]

set_property PACKAGE_PIN N33 [get_ports FMC2_HPC_LA_P_26]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_26]
set_property PACKAGE_PIN N34 [get_ports FMC2_HPC_LA_N_26]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_26]
set_property PACKAGE_PIN R33 [get_ports FMC2_HPC_LA_P_25]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_25]
set_property PACKAGE_PIN R34 [get_ports FMC2_HPC_LA_N_25]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_25]
set_property PACKAGE_PIN P35 [get_ports FMC2_HPC_LA_P_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_21]
set_property PACKAGE_PIN P36 [get_ports FMC2_HPC_LA_N_21]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_21]
set_property PACKAGE_PIN T32 [get_ports FMC2_HPC_LA_P_30]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_30]
set_property PACKAGE_PIN R32 [get_ports FMC2_HPC_LA_N_30]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_30]
set_property PACKAGE_PIN P32 [get_ports FMC2_HPC_LA_P_27]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_27]
set_property PACKAGE_PIN P33 [get_ports FMC2_HPC_LA_N_27]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_27]
set_property PACKAGE_PIN T36 [get_ports FMC2_HPC_LA_P_33]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_33]
set_property PACKAGE_PIN R37 [get_ports FMC2_HPC_LA_N_33]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_33]
set_property PACKAGE_PIN P37 [get_ports FMC2_HPC_LA_P_32]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_32]
set_property PACKAGE_PIN P38 [get_ports FMC2_HPC_LA_N_32]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_32]
set_property PACKAGE_PIN U34 [get_ports FMC2_HPC_LA_P_24]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_24]
set_property PACKAGE_PIN T35 [get_ports FMC2_HPC_LA_N_24]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_24]
set_property PACKAGE_PIN R38 [get_ports FMC2_HPC_LA_P_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_23]
set_property PACKAGE_PIN R39 [get_ports FMC2_HPC_LA_N_23]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_23]
set_property PACKAGE_PIN U37 [get_ports FMC2_HPC_LA_P_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_17]
set_property PACKAGE_PIN U38 [get_ports FMC2_HPC_LA_N_17]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_17]
set_property PACKAGE_PIN U39 [get_ports FMC2_HPC_CLK_M2C_P_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_CLK_M2C_P_1]
set_property PACKAGE_PIN T39 [get_ports FMC2_HPC_CLK_M2C_N_1]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_CLK_M2C_N_1]
set_property PACKAGE_PIN U36 [get_ports FMC2_HPC_LA_P_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_18]
set_property PACKAGE_PIN T37 [get_ports FMC2_HPC_LA_N_18]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_18]
set_property PACKAGE_PIN V35 [get_ports FMC2_HPC_LA_P_28]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_28]
set_property PACKAGE_PIN V36 [get_ports FMC2_HPC_LA_N_28]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_28]
set_property PACKAGE_PIN V33 [get_ports FMC2_HPC_LA_P_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_20]
set_property PACKAGE_PIN V34 [get_ports FMC2_HPC_LA_N_20]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_20]
set_property PACKAGE_PIN W36 [get_ports FMC2_HPC_LA_P_29]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_29]
set_property PACKAGE_PIN W37 [get_ports FMC2_HPC_LA_N_29]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_29]
set_property PACKAGE_PIN U32 [get_ports FMC2_HPC_LA_P_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_19]
set_property PACKAGE_PIN U33 [get_ports FMC2_HPC_LA_N_19]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_19]
set_property PACKAGE_PIN W32 [get_ports FMC2_HPC_LA_P_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_22]
set_property PACKAGE_PIN W33 [get_ports FMC2_HPC_LA_N_22]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_22]
set_property PACKAGE_PIN V39 [get_ports FMC2_HPC_LA_P_31]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_P_31]
set_property PACKAGE_PIN V40 [get_ports FMC2_HPC_LA_N_31]
set_property IOSTANDARD LVCMOS18 [get_ports FMC2_HPC_LA_N_31]

set_property PACKAGE_PIN P4 [get_ports FMC2_HPC_DP_C2M_P_7]
set_property PACKAGE_PIN R6 [get_ports FMC2_HPC_DP_M2C_P_7]
set_property PACKAGE_PIN P3 [get_ports FMC2_HPC_DP_C2M_N_7]
set_property PACKAGE_PIN R5 [get_ports FMC2_HPC_DP_M2C_N_7]
set_property PACKAGE_PIN R2 [get_ports FMC2_HPC_DP_C2M_P_6]
set_property PACKAGE_PIN U6 [get_ports FMC2_HPC_DP_M2C_P_6]
set_property PACKAGE_PIN R1 [get_ports FMC2_HPC_DP_C2M_N_6]
set_property PACKAGE_PIN T8 [get_ports FMC2_HPC_GBTCLK_M2C_P_1]
set_property PACKAGE_PIN U5 [get_ports FMC2_HPC_DP_M2C_N_6]
set_property PACKAGE_PIN T7 [get_ports FMC2_HPC_GBTCLK_M2C_N_1]

set_property PACKAGE_PIN T4 [get_ports FMC2_HPC_DP_C2M_P_5]
set_property PACKAGE_PIN V4 [get_ports FMC2_HPC_DP_M2C_P_5]
set_property PACKAGE_PIN T3 [get_ports FMC2_HPC_DP_C2M_N_5]
set_property PACKAGE_PIN V3 [get_ports FMC2_HPC_DP_M2C_N_5]
set_property PACKAGE_PIN U2 [get_ports FMC2_HPC_DP_C2M_P_4]
set_property PACKAGE_PIN W6 [get_ports FMC2_HPC_DP_M2C_P_4]
set_property PACKAGE_PIN U1 [get_ports FMC2_HPC_DP_C2M_N_4]
set_property PACKAGE_PIN W5 [get_ports FMC2_HPC_DP_M2C_N_4]
set_property PACKAGE_PIN K4 [get_ports FMC2_HPC_DP_C2M_P_3]
set_property PACKAGE_PIN J6 [get_ports FMC2_HPC_DP_M2C_P_3]
set_property PACKAGE_PIN K3 [get_ports FMC2_HPC_DP_C2M_N_3]
set_property PACKAGE_PIN J5 [get_ports FMC2_HPC_DP_M2C_N_3]
set_property PACKAGE_PIN L2 [get_ports FMC2_HPC_DP_C2M_P_2]
set_property PACKAGE_PIN L6 [get_ports FMC2_HPC_DP_M2C_P_2]
set_property PACKAGE_PIN L1 [get_ports FMC2_HPC_DP_C2M_N_2]
set_property PACKAGE_PIN K8 [get_ports FMC2_HPC_GBTCLK_M2C_P_0]
set_property PACKAGE_PIN L5 [get_ports FMC2_HPC_DP_M2C_N_2]
set_property PACKAGE_PIN K7 [get_ports FMC2_HPC_GBTCLK_M2C_N_0]

# Voltage adjust
set_property PACKAGE_PIN AH35 [get_ports FMC_VADJ_ON_B_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC_VADJ_ON_B_LS]

# IDK WTH THIS IS
set_property PACKAGE_PIN AL32 [get_ports FMC_C2M_PG_LS]
set_property IOSTANDARD LVCMOS18 [get_ports FMC_C2M_PG_LS]
