set_property CFGBVS GND                               [current_design]
set_property CONFIG_VOLTAGE 1.8                       [current_design]

create_clock -name sys_diff_clk -period 5.0 [get_ports sys_clock_p]
set_input_jitter [get_clocks -of_objects [get_ports sys_clock_p]] 0.5
create_clock -name JTCK -period 100.0 [get_ports {K_HEADER_5}]
set_input_jitter JTCK 0.5

set_clock_groups -asynchronous \
  -group [list [get_clocks { \
      sys_diff_clk \
    }]] \
  -group [list [get_clocks { \
      txoutclk \
      userclk1 \
    }]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out1 \
    }]]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out2 \
    }]]] \
  -group [list [get_clocks -of_objects [get_pins { \
      pll/clk_out3 \
    }]]] \
  -group [list [get_clocks { \
      JTCK \
    }]] \
  -group [list [get_clocks -of_objects [get_pins { \
      mod_1/clockctrlClockDomainWrapper/clockctrl_0/mmcme2_adv_inst/CLKOUT0 \
    }]]]

# Nah, definitelly quit here. Going to put the false path in the clock
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {K_HEADER_5}]]

# Table 14
set_property PACKAGE_PIN {L23} [get_ports {rst_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports {rst_0}]

# Table 13
set_property PACKAGE_PIN {AB2} [get_ports {sys_clock_p}]
set_property PACKAGE_PIN {AC2} [get_ports {sys_clock_n}]
set_property IOSTANDARD DIFF_HSTL_I [get_ports {sys_clock_p}]
set_property IOSTANDARD DIFF_HSTL_I [get_ports {sys_clock_n}]

# Table 19
set_property PACKAGE_PIN {D19} [get_ports {K_HEADER_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_0]
set_property PACKAGE_PIN {N17} [get_ports {K_HEADER_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_1]
set_property PACKAGE_PIN {N16} [get_ports {K_HEADER_2}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_2]
set_property PACKAGE_PIN {P24} [get_ports {K_HEADER_3}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_3]
set_property PACKAGE_PIN {E23} [get_ports {K_HEADER_4}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_4]
set_property PACKAGE_PIN {F22} [get_ports {K_HEADER_5}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_5]
set_property PACKAGE_PIN {F23} [get_ports {K_HEADER_6}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_6]
set_property PACKAGE_PIN {G22} [get_ports {K_HEADER_7}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_7]
set_property PACKAGE_PIN {F24} [get_ports {K_HEADER_8}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_8]
set_property PACKAGE_PIN {G24} [get_ports {K_HEADER_9}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_HEADER_9]
set_property PACKAGE_PIN {H18} [get_ports {K_CLK_EXT_N_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_CLK_EXT_N_0]
set_property PACKAGE_PIN {H17} [get_ports {K_CLK_EXT_P_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_CLK_EXT_P_0]
set_property PACKAGE_PIN {F18} [get_ports {K_CLK_EXT_N_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_CLK_EXT_N_1]
set_property PACKAGE_PIN {G17} [get_ports {K_CLK_EXT_P_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_CLK_EXT_P_1]
set_property PACKAGE_PIN {D24} [get_ports {K_RSVIO_N_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_RSVIO_N_0]
set_property PACKAGE_PIN {D23} [get_ports {K_RSVIO_P_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_RSVIO_P_0]

# Table 17
set_property PACKAGE_PIN {J21} [get_ports {K_DIPSW_0}]
set_property PACKAGE_PIN {N19} [get_ports {K_DIPSW_1}]
set_property PACKAGE_PIN {M16} [get_ports {K_DIPSW_2}]
set_property PACKAGE_PIN {M20} [get_ports {K_DIPSW_3}]
set_property PACKAGE_PIN {L17} [get_ports {K_DIPSW_4}]
set_property PACKAGE_PIN {N24} [get_ports {K_DIPSW_5}]
set_property PACKAGE_PIN {K21} [get_ports {K_DIPSW_6}]
set_property PACKAGE_PIN {E21} [get_ports {K_DIPSW_7}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_2}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_3}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_4}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_5}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_6}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_DIPSW_7}]


# Table 20
set_property PACKAGE_PIN {G20} [get_ports {K_LED_0}]
set_property PACKAGE_PIN {L19} [get_ports {K_LED_1}]
set_property PACKAGE_PIN {K18} [get_ports {K_LED_2}]
set_property PACKAGE_PIN {H19} [get_ports {K_LED_3}]
set_property PACKAGE_PIN {K15} [get_ports {K_LED_4}]
set_property PACKAGE_PIN {P16} [get_ports {K_LED_5}]
set_property PACKAGE_PIN {T19} [get_ports {K_LED_6}]
set_property PACKAGE_PIN {T18} [get_ports {K_LED_7}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_2}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_3}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_4}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_5}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_6}]
set_property IOSTANDARD {LVCMOS25} [get_ports {K_LED_7}]



# Table 18
set_property PACKAGE_PIN {E17} [get_ports {K_FMC_CLK_M2C_N_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_CLK_M2C_N_0]
set_property PACKAGE_PIN {F17} [get_ports {K_FMC_CLK_M2C_P_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_CLK_M2C_P_0]
set_property PACKAGE_PIN {D18} [get_ports {K_FMC_CLK_M2C_N_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_CLK_M2C_N_1]
set_property PACKAGE_PIN {E18} [get_ports {K_FMC_CLK_M2C_P_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_CLK_M2C_P_1]
set_property PACKAGE_PIN {F10} [get_ports {K_FMC_LA_N_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_0]
set_property PACKAGE_PIN {G11} [get_ports {K_FMC_LA_P_0}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_0]
set_property PACKAGE_PIN {D11} [get_ports {K_FMC_LA_N_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_1]
set_property PACKAGE_PIN {E11} [get_ports {K_FMC_LA_P_1}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_1]
set_property PACKAGE_PIN {E16} [get_ports {K_FMC_LA_N_2}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_2]
set_property PACKAGE_PIN {E15} [get_ports {K_FMC_LA_P_2}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_2]
set_property PACKAGE_PIN {D13} [get_ports {K_FMC_LA_N_3}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_3]
set_property PACKAGE_PIN {D14} [get_ports {K_FMC_LA_P_3}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_3]
set_property PACKAGE_PIN {F20} [get_ports {K_FMC_LA_N_4}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_4]
set_property PACKAGE_PIN {G19} [get_ports {K_FMC_LA_P_4}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_4]
set_property PACKAGE_PIN {D16} [get_ports {K_FMC_LA_N_5}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_5]
set_property PACKAGE_PIN {D15} [get_ports {K_FMC_LA_P_5}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_5]
set_property PACKAGE_PIN {B19} [get_ports {K_FMC_LA_N_6}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_6]
set_property PACKAGE_PIN {C19} [get_ports {K_FMC_LA_P_6}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_6]
set_property PACKAGE_PIN {A17} [get_ports {K_FMC_LA_N_7}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_7]
set_property PACKAGE_PIN {B17} [get_ports {K_FMC_LA_P_7}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_7]
set_property PACKAGE_PIN {E20} [get_ports {K_FMC_LA_N_8}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_8]
set_property PACKAGE_PIN {F19} [get_ports {K_FMC_LA_P_8}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_8]
set_property PACKAGE_PIN {A19} [get_ports {K_FMC_LA_N_9}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_9]
set_property PACKAGE_PIN {A18} [get_ports {K_FMC_LA_P_9}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_9]
set_property PACKAGE_PIN {C18} [get_ports {K_FMC_LA_N_10}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_10]
set_property PACKAGE_PIN {C17} [get_ports {K_FMC_LA_P_10}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_10]
set_property PACKAGE_PIN {G16} [get_ports {K_FMC_LA_N_11}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_11]
set_property PACKAGE_PIN {H16} [get_ports {K_FMC_LA_P_11}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_11]
set_property PACKAGE_PIN {B16} [get_ports {K_FMC_LA_N_12}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_12]
set_property PACKAGE_PIN {C16} [get_ports {K_FMC_LA_P_12}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_12]
set_property PACKAGE_PIN {A15} [get_ports {K_FMC_LA_N_13}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_13]
set_property PACKAGE_PIN {B15} [get_ports {K_FMC_LA_P_13}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_13]
set_property PACKAGE_PIN {F15} [get_ports {K_FMC_LA_N_14}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_14]
set_property PACKAGE_PIN {G15} [get_ports {K_FMC_LA_P_14}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_14]
set_property PACKAGE_PIN {A14} [get_ports {K_FMC_LA_N_15}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_15]
set_property PACKAGE_PIN {B14} [get_ports {K_FMC_LA_P_15}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_15]
set_property PACKAGE_PIN {E12} [get_ports {K_FMC_LA_N_16}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_16]
set_property PACKAGE_PIN {E13} [get_ports {K_FMC_LA_P_16}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_16]
set_property PACKAGE_PIN {C11} [get_ports {K_FMC_LA_N_17}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_17]
set_property PACKAGE_PIN {C12} [get_ports {K_FMC_LA_P_17}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_17]
set_property PACKAGE_PIN {D10} [get_ports {K_FMC_LA_N_18}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_18]
set_property PACKAGE_PIN {E10} [get_ports {K_FMC_LA_P_18}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_18]
set_property PACKAGE_PIN {D8} [get_ports {K_FMC_LA_N_19}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_19]
set_property PACKAGE_PIN {D9} [get_ports {K_FMC_LA_P_19}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_19]
set_property PACKAGE_PIN {G9} [get_ports {K_FMC_LA_N_20}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_20]
set_property PACKAGE_PIN {G10} [get_ports {K_FMC_LA_P_20}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_20]
set_property PACKAGE_PIN {A12} [get_ports {K_FMC_LA_N_21}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_21]
set_property PACKAGE_PIN {A13} [get_ports {K_FMC_LA_P_21}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_21]
set_property PACKAGE_PIN {F8} [get_ports {K_FMC_LA_N_22}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_22]
set_property PACKAGE_PIN {F9} [get_ports {K_FMC_LA_P_22}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_22]
set_property PACKAGE_PIN {J16} [get_ports {K_FMC_LA_N_23}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_23]
set_property PACKAGE_PIN {J15} [get_ports {K_FMC_LA_P_23}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_23]
set_property PACKAGE_PIN {H8} [get_ports {K_FMC_LA_N_24}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_24]
set_property PACKAGE_PIN {H9} [get_ports {K_FMC_LA_P_24}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_24]
set_property PACKAGE_PIN {F13} [get_ports {K_FMC_LA_N_25}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_25]
set_property PACKAGE_PIN {F14} [get_ports {K_FMC_LA_P_25}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_25]
set_property PACKAGE_PIN {H13} [get_ports {K_FMC_LA_N_26}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_26]
set_property PACKAGE_PIN {J13} [get_ports {K_FMC_LA_P_26}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_26]
set_property PACKAGE_PIN {B11} [get_ports {K_FMC_LA_N_27}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_27]
set_property PACKAGE_PIN {B12} [get_ports {K_FMC_LA_P_27}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_27]
set_property PACKAGE_PIN {B9} [get_ports {K_FMC_LA_N_28}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_28]
set_property PACKAGE_PIN {C9} [get_ports {K_FMC_LA_P_28}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_28]
set_property PACKAGE_PIN {A8} [get_ports {K_FMC_LA_N_29}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_29]
set_property PACKAGE_PIN {A9} [get_ports {K_FMC_LA_P_29}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_29]
set_property PACKAGE_PIN {F12} [get_ports {K_FMC_LA_N_30}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_30]
set_property PACKAGE_PIN {G12} [get_ports {K_FMC_LA_P_30}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_30]
set_property PACKAGE_PIN {J10} [get_ports {K_FMC_LA_N_31}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_31]
set_property PACKAGE_PIN {J11} [get_ports {K_FMC_LA_P_31}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_31]
set_property PACKAGE_PIN {A10} [get_ports {K_FMC_LA_N_32}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_32]
set_property PACKAGE_PIN {B10} [get_ports {K_FMC_LA_P_32}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_32]
set_property PACKAGE_PIN {G14} [get_ports {K_FMC_LA_N_33}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_N_33]
set_property PACKAGE_PIN {H14} [get_ports {K_FMC_LA_P_33}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_LA_P_33]
set_property PACKAGE_PIN {U16} [get_ports {K_FMC_PG_EN}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_PG_EN]
set_property PACKAGE_PIN {J14} [get_ports {K_FMC_PRSNT_B}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_PRSNT_B]
set_property PACKAGE_PIN {C14} [get_ports {K_FMC_SCL_2V5}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_SCL_2V5]
set_property PACKAGE_PIN {C13} [get_ports {K_FMC_SDA_2V5}]
set_property IOSTANDARD {LVCMOS25} [get_ports K_FMC_SDA_2V5]




